sonar.projectKey=dfavacho-sp_fc2-sonarcloud
sonar.organization=dfavacho-sp

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
# sonar.host.url=http://localhost:9000 
# sonar.login=sqp_e350c0fbc366bb2e267eb57268634f6cf0be3a59